# Generated by Django 3.1.7 on 2021-03-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210328_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
